### ISSUE TITLE
fwrite(): Argument #1 ($stream) must be of type resource at class-letsencrypt-handler.php:1166

### ISSUE THREAD

**Issue by sknurujjaman** [Really-Simple-Plugins/really-simple-ssl#415]
Hi,
When applying Install SSL Certificate, I am getting the below error:
CRITICAL Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in /opt/lampp/htdocs/wp-content/plugins/really-simple-ssl/lets-encrypt/class-letsencrypt-handler.php:1166
Stack trace:
#0 /opt/lampp/htdocs/wp-content/plugins/really-simple-ssl/lets-encrypt/class-letsencrypt-handler.php(1166): fwrite(false, 'file to test wr...')
#1 /opt/lampp/htdocs/wp-content/plugins/really-simple-ssl/lets-encrypt/class-letsencrypt-handler.php(1314): rsssl_letsencrypt_handler->directory_has_writing_permissions(false)
#2 /opt/lampp/htdocs/wp-content/plugins/really-simple-ssl/lets-encrypt/class-letsencrypt-handler.php(42): rsssl_letsencrypt_handler->key_directory()
#3 /opt/lampp/htdocs/wp-content/plugins/really-simple-ssl/lets-encrypt/letsencrypt.php(69): rsssl_letsencrypt_handler->__construct()
#4 /opt/lampp/htdocs/wp-content/plugins/really-simple-ssl/lets-encrypt/letsencrypt.php(106): RSSSL_LETSENCRYPT::instance()
#5 /opt/lampp/htdocs/wp-includes/class-wp-hook.php(303): RSSSL_LE('')
#6 /opt/lampp/htdocs/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(Object(REALLY_SIMPLE_SSL), Array)
#7 /opt/lampp/htdocs/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /opt/lampp/htdocs/wp-settings.php(441): do_action('plugins_loaded')
#9 /opt/lampp/htdocs/wp-config.php(96): require_once('/opt/lampp/htdo...')
#10 /opt/lampp/htdocs/wp-load.php(50): require_once('/opt/lampp/htdo...')
#11 /opt/lampp/htdocs/wp-admin/admin.php(34): require_once('/opt/lampp/htdo...')
#12 /opt/lampp/htdocs/wp-admin/options-general.php(10): require_once('/opt/lampp/htdo...')
#13 {main}
  thrown in /opt/lampp/htdocs/wp-content/plugins/really-simple-ssl/lets-encrypt/class-letsencrypt-handler.php on line 1166

**Comment by rlankhorst** [comment]
Thanks for reporting the issue. The set_error_handler function normally catches this error. I have to investigate why this doesn't happen. Apparently there is no writing permission for the plugin. I'll get back to you on this.

**Comment by rlankhorst** [comment]
@sknurujjaman Can you try if this branch resolves your issue?
An extra test has been added to catch this error:

https://github.com/Really-Simple-Plugins/really-simple-ssl/tree/catch-not-existing-file-in-writing-permissions-test

**Comment by rlankhorst** [comment]
This is currently merged into master. I'm closing this now. Let me know if you run into any issues.
