### ISSUE TITLE
Incorrect modification to body tag by force HTTPS option in RSSSL Plugin v5.0.9/5.0.10

### ISSUE THREAD

**Issue by eqdev** [Really-Simple-Plugins/really-simple-ssl#420]
Hi

This is a bug report that you might like to know to assist. If you know already, or this is written in the wrong style or location, then never mind.

The inserted string `data-rsssl="1"` at the start of the `<body>` tag is now missing the closing doublequote and trailing space.

Therefore this ruins the remaining class declarations of the `<body>`.

So here is how it is **currently operating**:

Before:
`<body class="foo bar">`

After:
`<body data-rsssl="1class="foo bar">`

And here is **how it should** (this is what I think you intended):

Before:
`<body class="foo bar">`

After:
`<body data-rsssl="1" class="foo bar">`

Tested and verified on v5.0.9 / v5.0.10. May have arisen in 5.0.9 but that is speculation.

Deactivating the setting to force HTTPS (/fix mixed content) is a current stable workaround, but denies access to that functionality until this is corrected.

**Comment by rlankhorst** [comment]
This is interesting, as the plugin does not add quotes, see the line where the tag is added:

  $str = str_replace("<body", '<body data-rsssl=1', $str);

And we do not have a "force https" setting. 

Maybe another plugin is adding the quotes? Can check if deactivating other plugins resolves the issue?

**Comment by eqdev** [comment]
Thanks, sorry for the terminology confusion on "force https". The exact terminology used in the plugin is "Mixed content fixer". Switching that setting off (in this plugin) resolved it for me, though that is a workaround. I am just lucky that I do not need that setting.

Based on that line, I can't see it literally causing the issue unless there is some form of type mismatch, coercion artefact or encode/decode effects happening along the way unknowingly.

If you can replicate the issue, or if that line or its related mechanism have changed in the last couple of minor versions, you may wish to investigate further.

If not, I can understand if you prefer to close this issue and mark it resolved. It doesn't affect me either way.

Thanks and all the best.

**Comment by rlankhorst** [comment]
Hi @eqdev, 

I just checked this on some sites, for example on https://really-simple-ssl.com. As you can see, the mixed content fixer is active, and the data-rsssl=1 tag is added correctly. 

I suspect you have another plugin which is also editing the <body> element. If you know which plugin this is, I can add it to our incompatibility list.

**Comment by eqdev** [comment]
Ok. The plugins that edit that element are Jetpack, Mega Menu and RSSSSL. Of these, the one that caused my issue was the RSSSL plugin. I do not feel that you have enough information to add either of those other plugins to your incompatibility list. Since you could not replicate this issue, I will now close it.
