### ISSUE TITLE
renewing certificate won't generate a new one

### ISSUE THREAD

**Issue by markusd1984** [Really-Simple-Plugins/really-simple-ssl#458]
I downloaded the newly generated certificate but it's still showing the old expiration date of October and thus won't work anymore.

Despite stating in the Generation dialogue:

> Certificate already generated. It was renewed if required.

What may prevent this? I'm using 5.0.2 in WP.

**Comment by rlankhorst** [comment]
Can you try the "reset" button at the right top of the Let's Encrypt wizard? That should force the renewal again. If you're not updated to 5.2.0 yet, please update so you have the reset button. Then run the wizard again. 
This should resolve the issue.
