### ISSUE TITLE
zindex clash with popup

### ISSUE THREAD

**Issue by rtpHarry** [Really-Simple-Plugins/really-simple-ssl#543]
The popup goes behind the wordpress admin bar in certain screen sizes:

<img width="525" alt="image" src="https://user-images.githubusercontent.com/1038062/201472456-c8535bd7-58fc-4099-b657-caa7bb51cf77.png">

**Comment by rlankhorst** [comment]
@rtpHarry thanks for reporting, a fix has been created:
https://github.com/Really-Simple-Plugins/really-simple-ssl/compare/z-index-of-modal-?expand=1

It will get tested and merged soon I expect, as it is a small css tweak.
