### ISSUE TITLE
confusing experience with the rename admin user hardening rule

### ISSUE THREAD

**Issue by rtpHarry** [Really-Simple-Plugins/really-simple-ssl#544]
I'm on a site that doesn't have an 'admin' user but that rename admin user rule is still being flagged up.

When you click on it, the user name box comes up. I left it blank and it let me submit it / toggle the rule on.

That stopped the warnings / tasks around the plugin.

However, revisiting that page shows that username field still there on the page, which also seems wrong:

<img width="897" alt="image" src="https://user-images.githubusercontent.com/1038062/201472793-4c68473b-2f79-405c-919c-b504ace49bf8.png">

**Comment by rlankhorst** [comment]
Hi @rtpHarry, 
Thanks for reporting your experiences, this helps us a lot!

The UX for this feature can be improved, I agree. We're discussing options for this. 
It's strange that you get this notice (in the tasks overview?) if you don't have an admin user, as the function just checks if the username 'admin' exists. It is dismissible though. Or are you referring the the 'hardening features' list at the right? The tasks in the tasks overview at the left reflects the actual detected situation, the features on the right reflect the settings. 
 
Even if an admin user is not present, the feature itself is still useful as it also prevents new users with the admin username. But this requires a comment or tooltip. 

A simple improvement is to hide the username option if no admin user is present. I've just created a branch for this. It will get tested and merged in a future release. If there is no admin user, the username option is not useful. 
https://github.com/Really-Simple-Plugins/really-simple-ssl/tree/hide-username-option-if-no-admin-user-present

**Comment by rlankhorst** [comment]
@rtpHarry we've merged an improvement to this interface by hiding the new username field if there is not admin user present. 
More improvements will be added in coming releases. Thans for your feedback.
