### ISSUE TITLE
ob_end_flush(): Cannot use output buffering in output buffering display handlers 

### ISSUE THREAD

**Issue by jgarvel** [Really-Simple-Plugins/really-simple-ssl#597]
Hello, I use Oxygen Builder with Really Simple SSL plug-in, but recently I get this error: PHP Fatal error:  ob_end_flush(): Cannot use output buffering in output buffering display handlers in /.../wp-content/plugins/really-simple-ssl/class-mixed-content-fixer.php on line 107. I have the latest Oxygen version. I have to disable SSL to use Oxygen. Can you please help?

**Comment by rlankhorst** [comment]
It sounds like the oxygen builder is not closing the output buffer, or your server is running low on memory. You can increase it with:


define('WP_MEMORY_LIMIT', '256M');
