### ISSUE TITLE
setup wizard reverts enable security hardening back to enable

### ISSUE THREAD

**Issue by rtpHarry** [Really-Simple-Plugins/really-simple-ssl#600]
I've clicked enable and after it finishes, it reverts back to enable again:

<img width="846" alt="image" src="https://github.com/Really-Simple-Plugins/really-simple-ssl/assets/1038062/23974c5d-a787-4589-846a-3a72cc22c41d">

Clicking it again runs it through the process (installing message) and ends up back with enable still being visible.

**Comment by rlankhorst** [comment]
@rtpHarry I have fixed it here. The response from the plugin after completion was next_action:none. The react component listens to next_action:completed. 
Thanks for reporting! It will be merged soon. 

https://github.com/Really-Simple-Plugins/really-simple-ssl/tree/fix-'enabled'-to-'finished'-after-enabling-hardening-features
