### ISSUE TITLE
dashboard is showing incorrect info

### ISSUE THREAD

**Issue by rtpHarry** [Really-Simple-Plugins/really-simple-ssl#601]
Current view:

<img width="765" alt="image" src="https://github.com/Really-Simple-Plugins/really-simple-ssl/assets/1038062/8bcad584-9385-4dee-881a-33d6edd49d9d">

You can see top right 1 task, progress bar, 2 tasks.

I've noticed that after running the hardening, it doesn't clear out the "your wordpress version is visible" task. I manually X'd that just before this screenshot.

To see if the 2nd task was the 'upgrade' one, i also clicked X on the "database prefix is wp_", and it did a pulse on the progress bar, changed the % to 75, but didn't change the number of tasks.

Refreshing the page has fixed it now:

<img width="798" alt="image" src="https://github.com/Really-Simple-Plugins/really-simple-ssl/assets/1038062/51d3dc8c-e89d-465a-abbb-ca0ba4316477">

**Comment by rlankhorst** [comment]
Thanks for reporting it, we'll look into it 👍

**Comment by rtpHarry** [comment]
Hmm yes, it is possible that I had already enabled LiteSpeed cache, I usually set up this and the cache as part of the launch / migrate process so I couldn't tell you from memory if that was the scenario.

I wasn't sure what was going on exactly with this originally, but I think that I might have reported two things in one issue.

I think that one issue is the wp version visible not cancelling itself (because of the cache, maybe)

And another issue is that the two tasks counts seem to get out of sync. I will pay attention next time I install this, to see if I can spot what is happening a little better.

**Comment by rlankhorst** [comment]
@rtpHarry In our upcoming release the tasks count, and open tasks are correctly updating based on selected options in the modal, so I'm closing this issue. Let me know if you are still experiencing this.
